### ISSUE TITLE
Deadlock when returning from payment page to success page

### ISSUE THREAD

**Issue by leeuwd** [Adyen/magento#328]
The following deadlock occurred when returning from the Adyen creditcard payment page to the success page. The Magento fatal error page was shown instead.

I can't be sure this is an Adyen issue or has something to do with our specific setup. I do know that this error occurs more often on our production environment, but this is the first time I have seen it live. 

We're on Magento 1.9.1.1 and Adyen_Payment 2.3.0.

### Error
```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: UPDATE `sales_flat_order` SET `state` = ?, `status` = ?, `coupon_code` = ?, `protect_code` = ?, `shipping_description` = ?, `is_virtual` = ?, `store_id` = ?, `customer_id` = ?, `base_discount_amount` = ?, `base_discount_canceled` = ?, `base_discount_invoiced` = ?, `base_discount_refunded` = ?, `base_grand_total` = ?, `base_shipping_amount` = ?, `base_shipping_canceled` = ?, `base_shipping_invoiced` = ?, `base_shipping_refunded` = ?, `base_shipping_tax_amount` = ?, `base_shipping_tax_refunded` = ?, `base_subtotal` = ?, `base_subtotal_canceled` = ?, `base_subtotal_invoiced` = ?, `base_subtotal_refunded` = ?, `base_tax_amount` = ?, `base_tax_canceled` = ?, `base_tax_invoiced` = ?, `base_tax_refunded` = ?, `base_to_global_rate` = ?, `base_to_order_rate` = ?, `base_total_canceled` = ?, `base_total_invoiced` = ?, `base_total_invoiced_cost` = ?, `base_total_offline_refunded` = ?, `base_total_online_refunded` = ?, `base_total_paid` = ?, `base_total_qty_ordered` = ?, `base_total_refunded` = ?, `discount_amount` = ?, `discount_canceled` = ?, `discount_invoiced` = ?, `discount_refunded` = ?, `grand_total` = ?, `shipping_amount` = ?, `shipping_canceled` = ?, `shipping_invoiced` = ?, `shipping_refunded` = ?, `shipping_tax_amount` = ?, `shipping_tax_refunded` = ?, `store_to_base_rate` = ?, `store_to_order_rate` = ?, `subtotal` = ?, `subtotal_canceled` = ?, `subtotal_invoiced` = ?, `subtotal_refunded` = ?, `tax_amount` = ?, `tax_canceled` = ?, `tax_invoiced` = ?, `tax_refunded` = ?, `total_canceled` = ?, `total_invoiced` = ?, `total_offline_refunded` = ?, `total_online_refunded` = ?, `total_paid` = ?, `total_qty_ordered` = ?, `total_refunded` = ?, `can_ship_partially` = ?, `can_ship_partially_item` = ?, `customer_is_guest` = ?, `customer_note_notify` = ?, `billing_address_id` = ?, `customer_group_id` = ?, `edit_increment` = ?, `email_sent` = ?, `forced_shipment_with_invoice` = ?, `payment_auth_expiration` = ?, `quote_address_id` = ?, `quote_id` = ?, `shipping_address_id` = ?, `adjustment_negative` = ?, `adjustment_positive` = ?, `base_adjustment_negative` = ?, `base_adjustment_positive` = ?, `base_shipping_discount_amount` = ?, `base_subtotal_incl_tax` = ?, `base_total_due` = ?, `payment_authorization_amount` = ?, `shipping_discount_amount` = ?, `subtotal_incl_tax` = ?, `total_due` = ?, `weight` = ?, `customer_dob` = '1960-07-07 00:00:00', `increment_id` = ?, `applied_rule_ids` = ?, `base_currency_code` = ?, `customer_email` = ?, `customer_firstname` = ?, `customer_lastname` = ?, `customer_middlename` = ?, `customer_prefix` = ?, `customer_suffix` = ?, `customer_taxvat` = ?, `discount_description` = ?, `ext_customer_id` = ?, `ext_order_id` = ?, `global_currency_code` = ?, `hold_before_state` = ?, `hold_before_status` = ?, `order_currency_code` = ?, `original_increment_id` = ?, `relation_child_id` = ?, `relation_child_real_id` = ?, `relation_parent_id` = ?, `relation_parent_real_id` = ?, `remote_ip` = ?, `shipping_method` = ?, `store_currency_code` = ?, `store_name` = ?, `x_forwarded_for` = ?, `customer_note` = ?, `created_at` = '2015-06-19 07:38:31', `updated_at` = '2015-06-19 07:38:41', `total_item_count` = ?, `customer_gender` = ?, `hidden_tax_amount` = ?, `base_hidden_tax_amount` = ?, `shipping_hidden_tax_amount` = ?, `base_shipping_hidden_tax_amnt` = ?, `hidden_tax_invoiced` = ?, `base_hidden_tax_invoiced` = ?, `hidden_tax_refunded` = ?, `base_hidden_tax_refunded` = ?, `shipping_incl_tax` = ?, `base_shipping_incl_tax` = ?, `coupon_rule_name` = ?, `paypal_ipn_customer_notified` = ?, `gift_message_id` = ?, `adyen_event_code` = ?, `ebizmarts_abandonedcart_flag` = ?, `ebizmarts_magemonkey_campaign_id` = ?, `additional_cost` = ?, `base_additional_cost` = ?, `additional_discount` = ?, `tryon_state` = ?, `adyen_boleto_pdf` = ?, `base_additional_discount` = ?, `customer_credit_amount` = ?, `base_customer_credit_amount` = ?, `customer_credit_invoiced` = ?, `base_customer_credit_invoiced` = ?, `customer_credit_refunded` = ?, `base_customer_credit_refunded` = ?, `discount_tax` = ?, `base_discount_tax` = ?, `payment_fee_amount` = ?, `base_payment_fee_amount` = ?, `payment_installment_fee_amount` = ?, `base_payment_installment_fee_amount` = ?, `insurance_claim_request` = ?, `asana_late_order_task_id` = ?, `asana_insurance_claim_task_id` = ?, `exclude_from_email_cycle` = ?, `sales_channel` = ?, `sales_channel_location` = ?, `sales_channel_data` = ? WHERE (entity_id='15138')

Trace:
#0 /staging_builds/1434638474/includes/src/Varien_Db_Statement_Pdo_Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /staging_builds/1434638474/includes/src/__default.php(65002): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /staging_builds/1434638474/includes/src/__default.php(54327): Zend_Db_Statement->execute(Array)
#3 /staging_builds/1434638474/includes/src/__default.php(55370): Zend_Db_Adapter_Abstract->query('UPDATE `sales_f...', Array)
#4 /staging_builds/1434638474/includes/src/__default.php(56230): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `sales_f...', Array)
#5 /staging_builds/1434638474/includes/src/__default.php(54482): Varien_Db_Adapter_Pdo_Mysql->query('UPDATE `sales_f...', Array)
#6 /staging_builds/1434638474/includes/src/__default.php(12371): Zend_Db_Adapter_Abstract->update('sales_flat_orde...', Array, 'entity_id='1513...')
#7 /staging_builds/1434638474/includes/src/Mage_Sales_Model_Resource_Order_Abstract.php(425): Mage_Core_Model_Resource_Db_Abstract->save(Object(Aceandtate_Prescription_Model_Order))
#8 /staging_builds/1434638474/includes/src/__default.php(5992): Mage_Sales_Model_Resource_Order_Abstract->save(Object(Aceandtate_Prescription_Model_Order))
#9 /staging_builds/1434638474/app/code/local/Aceandtate/Adyen/controllers/ProcessController.php(43): Mage_Core_Model_Abstract->save()
#10 /staging_builds/1434638474/includes/src/__default.php(14098): Aceandtate_Adyen_ProcessController->successAction()
#11 /staging_builds/1434638474/includes/src/__default.php(18515): Mage_Core_Controller_Varien_Action->dispatch('success')
#12 /staging_builds/1434638474/includes/src/__default.php(18045): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /staging_builds/1434638474/includes/src/__default.php(20862): Mage_Core_Controller_Varien_Front->dispatch()
#14 /staging_builds/1434638474/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /staging_contents/index.php(75): Mage::run('nl', 'store')
#16 {main}
```

### Request:

```
2015-06-19T07:38:31+00:00 DEBUG (7): Array
(
    [merchantAccount] => AceTateNL
    [merchantReference] => 100011397-try-on
    [paymentAmount] => 0
    [currencyCode] => EUR
    [shipBeforeDate] => 2015-07-03
    [skinCode] => CcWbwVoz
    [shopperLocale] => nl_NL
    [countryCode] => NL
    [shopperIP] => 193.173.40.4
    [browserInfo] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
    [orderData] => H4sIAAAAAAAAAw3MOw6AIBQEwKvsBYTCllATGxsvwGeDJALmQUy8vXZTjTlXa4J1nHC9Eoe8y95wS8/ia/UoA79mGQobEYWpzOglZWY+bAOpsLHBXwOhS1ZGB2v0335K46UPWwAAAA==
    [sessionValidity] => 2015-06-19T08:38:31+00:00
    [shopperEmail] => ****@mail.com (redacted)
    [recurringContract] => RECURRING
    [shopperReference] => 8073
    [blockedMethods] => 
    [merchantReturnData] => 
    [billingAddressType] => 
    [deliveryAddressType] => 
    [shopperType] => 
    [merchantSig] => I6RwfJcS5IVJ82SSjsG9kDVunpQ=
    [shopper.firstName] => Dick
    [shopper.lastName] => de Leeuw
    [billingAddress.street] => ***** (redacted)
    [billingAddress.houseNumberOrName] => 30
    [billingAddress.city] => *** (redacted)
    [billingAddress.postalCode] => **** (redacted)
    [billingAddress.stateOrProvince] => 
    [billingAddress.country] => NL
    [billingAddressSig] => b5oXM97AdVqhOKicFon4KCjdeiU=
    [deliveryAddress.street] => **** (redacted)
    [deliveryAddress.houseNumberOrName] => 30
    [deliveryAddress.city] => **** (redacted)
    [deliveryAddress.postalCode] => **** (redacted)
    [deliveryAddress.stateOrProvince] => 
    [deliveryAddress.country] => NL
    [deliveryAddressSig] => b5oXM97AdVqhOKicFon4KCjdeiU=
    [shopper.gender] => MALE
    [shopper.infix] => Mr.
    [shopper.dateOfBirthDayOfMonth] => 07
    [shopper.dateOfBirthMonth] => 07
    [shopper.dateOfBirthYear] => 1960
    [shopper.telephoneNumber] => 34523452
    [openinvoicedata.line1.currencyCode] => EUR
    [openinvoicedata.line1.description] => Benjamin Try-On
    [openinvoicedata.line1.itemAmount] => 000
    [openinvoicedata.line1.itemVatAmount] => 000
    [openinvoicedata.line1.numberOfItems] => 1
    [openinvoicedata.line1.vatCategory] => None
    [openinvoicedata.numberOfLines] => 1
    [openinvoicedata.refundDescription] => Refund / Correction for 100011397-try-on
    [openinvoicedata.sig] => xRwlgeGv4S7RKES0vvRtI6GnFs0=
)
```

### Notification:

```
2015-06-19T07:38:43+00:00 DEBUG (7): Array
(
    [processResponse begin] => Begin to process Notification
    [response] => stdClass Object
        (
            [additionalData] => Array
                (
                )

            [amount] => stdClass Object
                (
                    [currency] => EUR
                    [value] => 0
                )

            [eventCode] => AUTHORISATION
            [eventDate] => 2015-06-19T09:38:41.048+02:00
            [merchantAccountCode] => AceTateNL
            [merchantReference] => 100011397-try-on
            [operations] => stdClass Object
                (
                    [string] => Array
                        (
                            [0] => CANCEL
                            [1] => CAPTURE
                            [2] => REFUND
                        )

                )

            [originalReference] => 
            [paymentMethod] => mc
            [pspReference] => 8814346995215453
            [reason] => 79153:2909:6/2016
            [success] => 1
        )

    [_updateOrder] => Updating the order
    [_addStatusHistoryComment] => Created comment history for this notification
    [_updateAdyenAttributes] => Updating the Adyen attributes of the order
    [_processNotification] => Processing the notification
    [_authorizePayment] => Authorisation of the order
    [_setPrePaymentAuthorized] => No pre-authorised status is used so ignore
    [_prepareInvoice] => Prepare invoice for order
    [_createInvoice] => Creating invoice for order
    [_createInvoice error] => It is not possible to create invoice for this order
    [_storeNotification] => Notification is saved in adyen_event_data table
    [__pid] => 27241
)
```

**Comment by leeuwd** [comment]
Issue occurred again. On the following URL I got the Magento exception: `https://staging.aceandtate.com/adyen/process/success?merchantReference=100011401-try-on&skinCode=CcWbwVoz&shopperLocale=nl_NL&paymentMethod=mc&authResult=AUTHORISED&pspReference=8814347054871350&merchantSig=**********`

```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: UPDATE `sales_flat_order` SET `state` = ?, `status` = ?, `coupon_code` = ?, `protect_code` = ?, `shipping_description` = ?, `is_virtual` = ?, `store_id` = ?, `customer_id` = ?, `base_discount_amount` = ?, `base_discount_canceled` = ?, `base_discount_invoiced` = ?, `base_discount_refunded` = ?, `base_grand_total` = ?, `base_shipping_amount` = ?, `base_shipping_canceled` = ?, `base_shipping_invoiced` = ?, `base_shipping_refunded` = ?, `base_shipping_tax_amount` = ?, `base_shipping_tax_refunded` = ?, `base_subtotal` = ?, `base_subtotal_canceled` = ?, `base_subtotal_invoiced` = ?, `base_subtotal_refunded` = ?, `base_tax_amount` = ?, `base_tax_canceled` = ?, `base_tax_invoiced` = ?, `base_tax_refunded` = ?, `base_to_global_rate` = ?, `base_to_order_rate` = ?, `base_total_canceled` = ?, `base_total_invoiced` = ?, `base_total_invoiced_cost` = ?, `base_total_offline_refunded` = ?, `base_total_online_refunded` = ?, `base_total_paid` = ?, `base_total_qty_ordered` = ?, `base_total_refunded` = ?, `discount_amount` = ?, `discount_canceled` = ?, `discount_invoiced` = ?, `discount_refunded` = ?, `grand_total` = ?, `shipping_amount` = ?, `shipping_canceled` = ?, `shipping_invoiced` = ?, `shipping_refunded` = ?, `shipping_tax_amount` = ?, `shipping_tax_refunded` = ?, `store_to_base_rate` = ?, `store_to_order_rate` = ?, `subtotal` = ?, `subtotal_canceled` = ?, `subtotal_invoiced` = ?, `subtotal_refunded` = ?, `tax_amount` = ?, `tax_canceled` = ?, `tax_invoiced` = ?, `tax_refunded` = ?, `total_canceled` = ?, `total_invoiced` = ?, `total_offline_refunded` = ?, `total_online_refunded` = ?, `total_paid` = ?, `total_qty_ordered` = ?, `total_refunded` = ?, `can_ship_partially` = ?, `can_ship_partially_item` = ?, `customer_is_guest` = ?, `customer_note_notify` = ?, `billing_address_id` = ?, `customer_group_id` = ?, `edit_increment` = ?, `email_sent` = ?, `forced_shipment_with_invoice` = ?, `payment_auth_expiration` = ?, `quote_address_id` = ?, `quote_id` = ?, `shipping_address_id` = ?, `adjustment_negative` = ?, `adjustment_positive` = ?, `base_adjustment_negative` = ?, `base_adjustment_positive` = ?, `base_shipping_discount_amount` = ?, `base_subtotal_incl_tax` = ?, `base_total_due` = ?, `payment_authorization_amount` = ?, `shipping_discount_amount` = ?, `subtotal_incl_tax` = ?, `total_due` = ?, `weight` = ?, `customer_dob` = '1960-07-07 00:00:00', `increment_id` = ?, `applied_rule_ids` = ?, `base_currency_code` = ?, `customer_email` = ?, `customer_firstname` = ?, `customer_lastname` = ?, `customer_middlename` = ?, `customer_prefix` = ?, `customer_suffix` = ?, `customer_taxvat` = ?, `discount_description` = ?, `ext_customer_id` = ?, `ext_order_id` = ?, `global_currency_code` = ?, `hold_before_state` = ?, `hold_before_status` = ?, `order_currency_code` = ?, `original_increment_id` = ?, `relation_child_id` = ?, `relation_child_real_id` = ?, `relation_parent_id` = ?, `relation_parent_real_id` = ?, `remote_ip` = ?, `shipping_method` = ?, `store_currency_code` = ?, `store_name` = ?, `x_forwarded_for` = ?, `customer_note` = ?, `created_at` = '2015-06-19 09:18:01', `updated_at` = '2015-06-19 09:18:08', `total_item_count` = ?, `customer_gender` = ?, `hidden_tax_amount` = ?, `base_hidden_tax_amount` = ?, `shipping_hidden_tax_amount` = ?, `base_shipping_hidden_tax_amnt` = ?, `hidden_tax_invoiced` = ?, `base_hidden_tax_invoiced` = ?, `hidden_tax_refunded` = ?, `base_hidden_tax_refunded` = ?, `shipping_incl_tax` = ?, `base_shipping_incl_tax` = ?, `coupon_rule_name` = ?, `paypal_ipn_customer_notified` = ?, `gift_message_id` = ?, `adyen_event_code` = ?, `ebizmarts_abandonedcart_flag` = ?, `ebizmarts_magemonkey_campaign_id` = ?, `additional_cost` = ?, `base_additional_cost` = ?, `additional_discount` = ?, `tryon_state` = ?, `adyen_boleto_pdf` = ?, `base_additional_discount` = ?, `customer_credit_amount` = ?, `base_customer_credit_amount` = ?, `customer_credit_invoiced` = ?, `base_customer_credit_invoiced` = ?, `customer_credit_refunded` = ?, `base_customer_credit_refunded` = ?, `discount_tax` = ?, `base_discount_tax` = ?, `payment_fee_amount` = ?, `base_payment_fee_amount` = ?, `payment_installment_fee_amount` = ?, `base_payment_installment_fee_amount` = ?, `insurance_claim_request` = ?, `asana_late_order_task_id` = ?, `asana_insurance_claim_task_id` = ?, `exclude_from_email_cycle` = ?, `sales_channel` = ?, `sales_channel_location` = ?, `sales_channel_data` = ? WHERE (entity_id='15150')

Trace:
#0 /staging_builds/1434638474/includes/src/Varien_Db_Statement_Pdo_Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /staging_builds/1434638474/includes/src/__default.php(65002): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /staging_builds/1434638474/includes/src/__default.php(54327): Zend_Db_Statement->execute(Array)
#3 /staging_builds/1434638474/includes/src/__default.php(55370): Zend_Db_Adapter_Abstract->query('UPDATE `sales_f...', Array)
#4 /staging_builds/1434638474/includes/src/__default.php(56230): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `sales_f...', Array)
#5 /staging_builds/1434638474/includes/src/__default.php(54482): Varien_Db_Adapter_Pdo_Mysql->query('UPDATE `sales_f...', Array)
#6 /staging_builds/1434638474/includes/src/__default.php(12371): Zend_Db_Adapter_Abstract->update('sales_flat_orde...', Array, 'entity_id='1515...')
#7 /staging_builds/1434638474/includes/src/Mage_Sales_Model_Resource_Order_Abstract.php(425): Mage_Core_Model_Resource_Db_Abstract->save(Object(Aceandtate_Prescription_Model_Order))
#8 /staging_builds/1434638474/includes/src/__default.php(5992): Mage_Sales_Model_Resource_Order_Abstract->save(Object(Aceandtate_Prescription_Model_Order))
#9 /staging_builds/1434638474/app/code/local/Aceandtate/Adyen/controllers/ProcessController.php(43): Mage_Core_Model_Abstract->save()
#10 /staging_builds/1434638474/includes/src/__default.php(14098): Aceandtate_Adyen_ProcessController->successAction()
#11 /staging_builds/1434638474/includes/src/__default.php(18515): Mage_Core_Controller_Varien_Action->dispatch('success')
#12 /staging_builds/1434638474/includes/src/__default.php(18045): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /staging_builds/1434638474/includes/src/__default.php(20862): Mage_Core_Controller_Varien_Front->dispatch()
#14 /staging_builds/1434638474/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 staging_contents/index.php(75): Mage::run('nl', 'store')
#16 {main}
```

**Comment by leeuwd** [comment]
Did some debugging: when issue occurs, `Adyen_Payment_ProcessController::successAction` is started, but not finished.

**Comment by rikterbeek** [comment]
Hi Leeuwd,

Could you debug where is is going wrong. With an AUTHORISED result url it is not doing anything only logging and saving of the order. It looks like you have a problem with the save() function do you have external code or module that does something when the order is saved ?

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
I have found the problem, and its because of our custom edits. We extend `Adyen_Payment_ProcessController::successAction` to set a custom order history message. This includes a call to `$order->save();`. The latter leads to a deadlock in some cases (i.e., slow/fast database query). 

Our solution was to just drop the custom order history message, since it was not essential for us. The problem is solved and can be closed. Good for future reference for others with the same issue though.

Thanks for the quick response!

**Comment by adyenpayments** [comment]
Hi Leeuwd,

No problem. I am glad that you find and solved the issue.

Regards,
Rik
Adyen
