### ISSUE TITLE
Manual execution of queue item is broken in 2.3.0

### ISSUE THREAD

**Issue by jeroenvermeulen** [Adyen/magento#345]
In version 2.3.0:
* Go to Magento Backend
* Click  Sales > Adyen Notification Queue
* In a queue item select the action "Execute"

Error:
```
Invalid method Adyen_Payment_Model_Process::_processNotifications(Array)
#0 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php(75): Varien_Object->__call('_processNotific...', Array)
#1 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php(75): Adyen_Payment_Model_Process->_processNotifications(Object(Mage_Sales_Model_Order), Object(Varien_Object))
#2 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_Adminhtml_Adyen_Event_QueueController->executeAction()
#3 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('execute')
#4 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#6 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /data/vhosts/staging2.onderdelenwinkel.nl/httpdocs/index.live.php(87): Mage::run('default', 'store')
#8 {main}
```

I have made a workaround, diff below.
It is kind of dirty because I made a method public that was previously protected.

```
diff --git a/app/code/community/Adyen/Payment/Model/ProcessNotification.php b/app/code/community/Adyen/Payment/Model/ProcessNotification.php
index 5930ecf..ad40743 100644
--- a/app/code/community/Adyen/Payment/Model/ProcessNotification.php
+++ b/app/code/community/Adyen/Payment/Model/ProcessNotification.php
@@ -196,7 +196,7 @@ class Adyen_Payment_Model_ProcessNotification extends Mage_Core_Model_Abstract {
      * @param $order
      * @param $params
      */
-    protected function _updateOrder($order, $params)
+    public function _updateOrder($order, $params)
     {
         $this->_debugData['_updateOrder'] = 'Updating the order';

diff --git a/app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php b/app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php
index 4027960..f7063c4 100644
--- a/app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php
+++ b/app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php
@@ -72,7 +72,7 @@ class Adyen_Payment_Adminhtml_Adyen_Event_QueueController extends Mage_Adminhtml
             $order->loadByIncrementId($incrementId);

             // process it
-            Mage::getModel('adyen/process')->_processNotifications($order, $varienObj);
+            Mage::getModel('adyen/processNotification')->_updateOrder($order, $varienObj);

             // remove it from queue
             $eventQueue->delete();
```

**Comment by rikterbeek** [comment]
Hi Jeroen,

Many thanks for addressing this. We have forgot the test this part and it is now broken indeed.
I have fix it a little bit differently see commit below.

Regards,
Rik
Adyen
