### ISSUE TITLE
pack(): illegal hex digit with Mage::setIsDeveloperMode(true)

### ISSUE THREAD

**Issue by simonrl** [Adyen/magento#419]
Hi,

when I enable Developer Mode in my staging system, I have the following error logged when I go to my checkout page:

```
2015-09-22T13:34:04+00:00 ERR (3):
exception 'Exception' with message 'Warning: pack(): Type H: illegal hex digit W  in [PATH_TO_MAGENTO]/app/code/community/Adyen/Payment/Model/Observer.php on line 397' in [PATH_TO_MAGENTO]/app/code/core/Mage/Core/functions.php:245
Stack trace:
#0 [internal function]: mageCoreErrorHandler(2, 'pack(): Type H:...', '/var/www/vhosts...', 397, Array)
#1 [PATH_TO_MAGENTO]/app/code/community/Adyen/Payment/Model/Observer.php(397): pack('H*', '[MY_SKIN_HMAC]')
#2 [PATH_TO_MAGENTO]/app/code/community/Adyen/Payment/Model/Observer.php(262): Adyen_Payment_Model_Observer->_signRequestParams(Array, Object(Mage_Core_Model_Store))
#3 [PATH_TO_MAGENTO]/app/code/community/Adyen/Payment/Model/Observer.php(127): Adyen_Payment_Model_Observer->_getDirectoryLookupResponse(Array, Object(Mage_Core_Model_Store))
#4 [PATH_TO_MAGENTO]/app/code/community/Adyen/Payment/Model/Observer.php(61): Adyen_Payment_Model_Observer->_fetchHppMethods(Object(Mage_Core_Model_Store))
#5 [PATH_TO_MAGENTO]/app/code/community/Adyen/Payment/Model/Observer.php(42): Adyen_Payment_Model_Observer->_addHppMethodsToConfig(Object(Mage_Core_Model_Store))
#6 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Model/App.php(1338): Adyen_Payment_Model_Observer->addMethodsToConfig(Object(Varien_Event_Observer))
#7 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Adyen_Payment_Model_Observer), 'addMethodsToCon...', Object(Varien_Event_Observer))
#8 [PATH_TO_MAGENTO]/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#9 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Controller/Varien/Action.php(528): Mage::dispatchEvent('controller_acti...', Array)
#10 [PATH_TO_MAGENTO]/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#11 [PATH_TO_MAGENTO]/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(51): Mage_Adminhtml_Controller_Action->preDispatch()
#12 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Controller/Varien/Action.php(408): Mage_Adminhtml_System_ConfigController->preDispatch()
#13 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#14 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 [PATH_TO_MAGENTO]/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#16 [PATH_TO_MAGENTO]/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#17 [PATH_TO_MAGENTO]/index.php(94): Mage::run('de', 'store')
#18 {main}
```
My live-skin-Hmac as well as test-skin-Hmac both contain non-Hex-characters such as W, Y...

I'm not sure what causes this issue, as in my live system, the payment works fine.

My staging system uses 2.4.0.1, and 2.2.2 on live.

**Comment by rikterbeek** [comment]
HI simonrl,

The 2.4.0.1 is a develop version. This is using our new HMAC signature HMAC256 logic. The old 2.2.2 is using HMAC SHA1 version. So on your test you need to use a different skin that uses this new hmac signature.

Regards,
Rik
Adyen

**Comment by simonrl** [comment]
Hi Rik,

thanks for the feedback.
Can you tell me the latest stable?

Thanks
Simon

**Comment by rikterbeek** [comment]
Hi Simon,

You can see here our latest stable releases: https://github.com/Adyen/magento/releases
We do not have a stable version ready with the new HMAC calculation so you need to use the old SHA1 signature.

Regards,
Rik
Adyen

**Comment by simonrl** [comment]
K, thanks.

Seems that this is not an issue then... can I close it myself? If so, where? Sorry, but I am not an experienced github user...

**Comment by rikterbeek** [comment]
Hi Simon,

No problem you should be able to close the issue you have created below.
I will just close it now.

Regards,
Rik
Adyen
