### ISSUE TITLE
When placing a non-adyen payment execption is logged:

### ISSUE THREAD

**Issue by paales** [Adyen/magento#439]
```
exception 'Exception' with message 'Warning: pack(): Type H: illegal hex digit N  in app/code/community/Adyen/Payment/Model/Observer.php on line 397' in app/code/local/Mage/Core/functions.php:245
Stack trace:
#0 [internal function]: mageCoreErrorHandler(2, 'pack(): Type H:...', '/Users/paul/Sit...', 397, Array)
#1 app/code/community/Adyen/Payment/Model/Observer.php(397): pack('H*', 'DONTKNOWIFTHISMUSTBESECURE')
#2 app/code/community/Adyen/Payment/Model/Observer.php(262): Adyen_Payment_Model_Observer->_signRequestParams(Array, Object(Mana_Seo_Rewrite_Store))
#3 app/code/community/Adyen/Payment/Model/Observer.php(127): Adyen_Payment_Model_Observer->_getDirectoryLookupResponse(Array, Object(Mana_Seo_Rewrite_Store))
#4 app/code/community/Adyen/Payment/Model/Observer.php(61): Adyen_Payment_Model_Observer->_fetchHppMethods(Object(Mana_Seo_Rewrite_Store))
#5 app/code/community/Adyen/Payment/Model/Observer.php(42): Adyen_Payment_Model_Observer->_addHppMethodsToConfig(Object(Mana_Seo_Rewrite_Store))
#6 app/code/core/Mage/Core/Model/App.php(1338): Adyen_Payment_Model_Observer->addMethodsToConfig(Object(Varien_Event_Observer))
#7 app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Adyen_Payment_Model_Observer), 'addMethodsToCon...', Object(Varien_Event_Observer))
#8 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#9 app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#10 app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#11 app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Core_Controller_Front_Action->preDispatch()
#12 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#13 .modman/Ho_OfflineMaintenance/app/code/local/Ho/OfflineMaintenance/Controller/Router/Standard.php(55): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Ho_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#16 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#17 index.php(83): Mage::run('', 'store')
#18 {main}
```

**Comment by rikterbeek** [comment]
Hi Paul,

Looks like your are using a skin code that uses the new encryption (hmac 256) signature. The current version does not allow this so throws this error back. Please define a skin that has the old (sha1) signature.

Regards,
Rik
Adyen
